apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

def nav_version = "2.9.8"

android {
    namespace 'me.ibrahimsn.app'
    compileSdk = 37

    defaultConfig {
        applicationId "me.ibrahimsn.app"
        minSdkVersion 32
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    buildFeatures {
        viewBinding true
        compose true
    }
}

dependencies {
    implementation project(":lib")
    implementation project(":compose")

    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'

    // Navigation Architecture Component
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
    implementation "androidx.navigation:navigation-compose:$nav_version"

    // Jetpack Compose
    implementation platform('androidx.compose:compose-bom:2026.08.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'
}
