apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

def nav_version = "2.9.8"

android {
    namespace 'me.ibrahimsn.app'
    compileSdk = 37

    defaultConfig {
        applicationId "me.ibrahimsn.app"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(":lib")

    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'

    // Navigation Architecture Component
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
}
